spring:
  datasource:
    ## MYSQL
    url: jdbc:mysql://localhost:3306/tesis?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  header: Authorization
  secret: clasemtesisbackend
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
